version: '3'

volumes:
  cockroach_data:
    driver: local
  caddy_data:
    driver: local

services:
  cockroach:
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - 26257:26257
  cassandra:
    image: cassandra:4
    ports:
      - 9042:9042
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
      CASSANDRA_DC: datacenter1
      CASSANDRA_CLUSER_NAME: cassandra
  keycloak:
    image: quay.io/phasetwo/keycloak-crdb:23.0.3
    volumes:
      - ${PWD}/core/target/keycloak-cassandra-extension-1.3.2-23.0.3-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-cassandra-extension.jar
      - ${PWD}/delay-kc.sh:/opt/keycloak/bin/delay-kc.sh
    environment:
      KC_DB: cockroach
      KC_HTTP_RELATIVE_PATH: /auth
      KC_TRANSACTION_XA_ENABLED: false
      KC_TRANSACTION_JTA_ENABLED: false
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL_HOST: cockroach
      KC_DB_URL_PORT: 26257
      KC_DB_URL_DATABASE: defaultdb
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: ''
      KC_DB_URL_PROPERTIES: '?'
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_LOG_LEVEL: DEBUG,de.arbeitsagentur.opdt:INFO
      KC_SPI_DATASTORE_PROVIDER: cassandra-legacy
      KC_SPI_DATASTORE_CASSANDRA_MAP_CACHE_MODE: true
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_PORT: 9042
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_CONTACT_POINTS: cassandra
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_USERNAME: cassandra
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_PASSWORD: cassandra
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_LOCAL_DATACENTER: datacenter1
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_KEYSPACE: test
      KC_SPI_CASSANDRA_CONNECTION_DEFAULT_REPLICATION_FACTOR: 1
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - cockroach
    entrypoint: /opt/keycloak/bin/delay-kc.sh --verbose start
  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://localhost:443 --to http://keycloak:8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
    depends_on:
      - keycloak
